"""
data_setup: This is a script that includes the legacy data 
"""

customers = [
    {"id": 1, "name": "IBM Corporation", "city": "Armonk, NY", "street": "The IBM Way", "contact": "1-800-CALL-IBM"},
    {"id": 2, "name": "Ege Consulting, Inc.", "city": "Miami, FL", "street": "14531 SW 76 Street", "contact": "www.ege.com"},
    {"id": 3, "name": "Alcatel - Lucent -new", "city": "Holmdel, NJ", "street": "100 Crawfords Corner Road", "contact": "www.lucent.com"},
    {"id": 4, "name": "Insight Technologies Group", "city": "St. Louis, MO", "street": "Hollenberg Drive West, Suite 203", "contact": "info@insight-tech.com"},
    {"id": 5, "name": "Rational Software Corporation", "city": "Santa Clara, CA", "street": "Better than ARGO way", "contact": "www.rational.com"},
    {"id": 6, "name": "Bell South", "city": "Atlanta, GA", "street": "Braves Parkway", "contact": "1-305-970-BELL"},
    {"id": 7, "name": "GE Corporation", "city": "New York, NY", "street": "100 Wall Street", "contact": "John Myers @ 1-202-452-8864"},
    {"id": 8, "name": "Comcast - NBC", "city": "New York, NY", "street": "Katy and Matt Plaza", "contact": "www.nbc.COMCAST.com"},
    {"id": 9, "name": "Ralston Purina", "city": "Armadillo, TX", "street": "12123 Dog Lane", "contact": "Susan Powers @ 1-614-556-4266"},
    {"id": 10, "name": "John Deere Corporation", "city": "West Lafayette, IN", "street": "One Greenway", "contact": "www.johndeere.com"},
    {"id": 11, "name": "Hilti GMBH & Co, KG", "city": "Zurich, Switzerland", "street": "Tobelstrasse 14", "contact": "+39-89787-562636"},
    {"id": 12, "name": "Kress und Soehne", "city": "Hechingen, Germany", "street": "Industriegebiet", "contact": "+49-711-246012"},
    {"id": 13, "name": "GemStone Corporation", "city": "Beaverton, OR", "street": "John von Neumann Drive", "contact": "ally McBeal @ www.gemstone.com"},
    {"id": 14, "name": "The Maibaum Coalition", "city": "Crepe Sushette, Greece", "street": "near Athens", "contact": "mai.baum.gr"},
    {"id": 15, "name": "Grabby Grubby Meast", "city": "Burlington, IL", "street": "123 Water Tower Circle", "contact": "meat.grub.com"},
    {"id": 16, "name": "Mast und Schotbruch", "city": "Hamburg, Germany", "street": "1776 Ronald McDonald Allee", "contact": "www.ham.burg.de"},
    {"id": 17, "name": "Golden Seventeen Corporation", "city": "Chicago, IL", "street": "North Bayshore Drive", "contact": "17@18.net"},
    {"id": 18, "name": "South by Southwest", "city": "Austin, TX", "street": "100 SquareMile Road", "contact": "1-800-sxs-west"},
    {"id": 19, "name": "Diamonds are Forever", "city": "Kapstadt, South Africa", "street": "allover there", "contact": "dia@south.africa.net"},
    {"id": 20, "name": "Diamond Corporation", "city": "Hillsboro, OR", "street": "Wacker Drive", "contact": "ceo@dia.com"},
    {"id": 21, "name": "Excelsior Mutants", "city": "Vancouver, WA", "street": "1 Columbia Circle", "contact": "van@celsius.net"},
    {"id": 22, "name": "Clever Building & Co.", "city": "Seattle, WA", "street": "Evergreen Parkview, stall #2", "contact": "clever@huland.net"},
    {"id": 23, "name": "Reams Paper and Sausage", "city": "Elburn, IL", "street": "IL Rt. 47", "contact": "hackebeil@reams.tv"},
    {"id": 24, "name": "Rivabeck Industrial Solutions", "city": "Sycamore, IL", "street": "5566 Moore Ct", "contact": "1-815-riv-beck"},
    {"id": 25, "name": "Asus Tech", "city": "Taiwan, TW", "street": "EllisWay Thoroughfare", "contact": "asus.tw"},
    {"id": 26, "name": "Hongkong Travel Ltd.", "city": "Hongkong", "street": "Sang Pang Wang", "contact": "hong.kong"},
    {"id": 27, "name": "Clowncar Development Subsidiaries", "city": "DesMoines, IA", "street": "1492 West Far Out Blvd", "contact": "clown.car.tv"},
    {"id": 28, "name": "Big and Lovely Partnership", "city": "Salt Lake City, UT", "street": "smack in the middle", "contact": "www.big.love.com"},
    {"id": 30, "name": "United we Parcel", "city": "Gremlin, FL", "street": "1 Ocean Drive", "contact": "united@ocean.com"},
    {"id": 33, "name": "Old Customer: 25-11-07 06:18", "city": "Dekalb, IL", "street": "PM 51", "contact": "www.niu.edu"},
    {"id": 40, "name": "Atelier graphique", "city": "Nantes, France", "street": "54, rue Royale", "contact": "40.32.2555"},
    {"id": 41, "name": "Signal Gift Stores", "city": "Las Vegas, NV", "street": "8489 Strong St.", "contact": "7025551838"},
    {"id": 42, "name": "Australian Collectors, Co.", "city": "Melbourne, Australia", "street": "636 St Kilda Road", "contact": "03 9520 4555"},
    {"id": 43, "name": "La Rochelle Gifts", "city": "Nantes, France", "street": "67, rue des Cinquante Otages", "contact": "40.67.8555"},
    {"id": 44, "name": "Baane Mini Imports", "city": "Stavern, Norway", "street": "Erling Skakkes gate 78", "contact": "07-98 9555"},
    {"id": 45, "name": "Mini Gifts Distributors Ltd.", "city": "San Rafael, CA", "street": "5677 Strong St.", "contact": "4155551450"},
    {"id": 46, "name": "Havel & Zbyszek Co", "city": "Warszawa, Poland", "street": "ul. Filtrowa 68", "contact": "(26) 642-7555"},
    {"id": 47, "name": "Blauer See Auto, Co.", "city": "Frankfurt, Germany", "street": "Lyonerstr. 34", "contact": "+49 69 66 90 2555"},
    {"id": 48, "name": "Mini Wheels Co.", "city": "San Francisco, CA", "street": "5557 North Pendale Street", "contact": "6505555787"},
    {"id": 49, "name": "Land of Toys Inc.", "city": "NYC, NY", "street": "897 Long Airport Avenue", "contact": "2125557818"},
    {"id": 50, "name": "Euro+ Shopping Channel", "city": "Madrid, Spain", "street": "C/ Moralzarzal, 86", "contact": "(91) 555 94 44"},
    {"id": 51, "name": "Volvo Model Replicas, Co", "city": "Luleå, Sweden", "street": "Berguvsvägen 8", "contact": "0921-12 3555"},
    {"id": 52, "name": "Danish Wholesale Imports", "city": "Kobenhavn, Denmark", "street": "Vinbæltet 34", "contact": "31 12 3555"},
    {"id": 53, "name": "Saveley & Henriot, Co.", "city": "Lyon, France", "street": "2, rue du Commerce", "contact": "78.32.5555"},
    {"id": 54, "name": "Dragon Souveniers, Ltd.", "city": "Singapore, Singapore", "street": "Bronz Sok.", "contact": "+65 221 7555"},
    {"id": 55, "name": "Muscle Machine Inc", "city": "NYC, NY", "street": "4092 Furth Circle", "contact": "2125557413"},
    {"id": 56, "name": "Diecast Classics Inc.", "city": "Allentown, PA", "street": "7586 Pompton St.", "contact": "2155551555"},
    {"id": 57, "name": "Technics Stores Inc.", "city": "Burlingame, CA", "street": "9408 Furth Circle", "contact": "6505556809"},
    {"id": 58, "name": "Handji Gifts& Co", "city": "Singapore, Singapore", "street": "106 Linden Road Sandown", "contact": "+65 224 1555"},
    {"id": 59, "name": "Herkku Gifts", "city": "Bergen, Norway", "street": "Brehmen St. 121", "contact": "+47 2267 3215"},
    {"id": 60, "name": "American Souvenirs Inc", "city": "New Haven, CT", "street": "149 Spinnaker Dr.", "contact": "2035557845"},
    {"id": 61, "name": "Porto Imports Co.", "city": "Lisboa, Portugal", "street": "Estrada da saúde n. 58", "contact": "(1) 356-5555"},
    {"id": 62, "name": "Daedalus Designs Imports", "city": "Lille, France", "street": "184, chaussée de Tournai", "contact": "20.16.1555"},
    {"id": 63, "name": "La Corne D'abondance, Co.", "city": "Paris, France", "street": "265, boulevard Charonne", "contact": "(1) 42.34.2555"},
    {"id": 64, "name": "Cambridge Collectables Co.", "city": "Cambridge, MA", "street": "4658 Baden Av.", "contact": "6175555555"},
    {"id": 65, "name": "Gift Depot Inc.", "city": "Bridgewater, CT", "street": "25593 South Bay Ln.", "contact": "2035552570"},
    {"id": 66, "name": "Osaka Souveniers Co.", "city": "Kita-ku, Japan", "street": "1-6-20 Dojima", "contact": "+81 06 6342 5555"},
    {"id": 67, "name": "Vitachrome Inc.", "city": "NYC, NY", "street": "2678 Kingston Rd.", "contact": "2125551500"},
    {"id": 68, "name": "Toys of Finland, Co.", "city": "Helsinki, Finland", "street": "Keskuskatu 45", "contact": "90-224 8555"},
    {"id": 69, "name": "AV Stores, Co.", "city": "Manchester, UK", "street": "Fauntleroy Circus", "contact": "(171) 555-1555"},
    {"id": 70, "name": "Clover Collections, Co.", "city": "Dublin, Ireland", "street": "25 Maiden Lane", "contact": "+353 1862 1555"},
    {"id": 71, "name": "Auto-Moto Classics Inc.", "city": "Brickhaven, MA", "street": "16780 Pompton St.", "contact": "6175558428"},
    {"id": 72, "name": "UK Collectables, Ltd.", "city": "Liverpool, UK", "street": "12, Berkeley Gardens Blvd", "contact": "(171) 555-2282"},
    {"id": 73, "name": "Canadian Gift Exchange Network", "city": "Vancouver, Canada", "street": "1900 Oak St.", "contact": "(604) 555-3392"},
    {"id": 74, "name": "Online Mini Collectables", "city": "Brickhaven, MA", "street": "7635 Spinnaker Dr.", "contact": "6175557555"},
    {"id": 75, "name": "Toys4GrownUps.com", "city": "Pasadena, CA", "street": "78934 Hillside Dr.", "contact": "6265557265"},
    {"id": 76, "name": "Asian Shopping Network, Co", "city": "Singapore, Singapore", "street": "Suntec Tower Three", "contact": "+612 9411 1555"},
    {"id": 77, "name": "Mini Caravy", "city": "Strasbourg, France", "street": "24, place Kléber", "contact": "88.60.1555"},
    {"id": 78, "name": "King Kong Collectables, Co.", "city": "Central Hong Kong, Hong Kong", "street": "Bank of China Tower", "contact": "+852 2251 1555"},
    {"id": 79, "name": "Enaco Distributors", "city": "Barcelona, Spain", "street": "Rambla de Cataluña, 23", "contact": "(93) 203 4555"},
    {"id": 80, "name": "Boards & Toys Co.", "city": "Glendale, CA", "street": "4097 Douglas Av.", "contact": "3105552373"},
    {"id": 81, "name": "Natürlich Autos", "city": "Cunewalde, Germany", "street": "Taucherstraße 10", "contact": "0372-555188"},
    {"id": 82, "name": "Heintze Collectables", "city": "Århus, Denmark", "street": "Smagsloget 45", "contact": "86 21 3555"},
    {"id": 83, "name": "Québec Home Shopping Network", "city": "Montréal, Canada", "street": "43 rue St. Laurent", "contact": "(514) 555-8054"},
    {"id": 84, "name": "ANG Resellers", "city": "Madrid, Spain", "street": "Gran Vía, 1", "contact": "(91) 745 6555"},
    {"id": 85, "name": "Collectable Mini Designs Co.", "city": "San Diego, CA", "street": "361 Furth Circle", "contact": "7605558146"},
    {"id": 86, "name": "giftsbymail.co.uk", "city": "Cowes, UK", "street": "Garden House", "contact": "(198) 555-8888"},
    {"id": 87, "name": "Alpha Cognac", "city": "Toulouse, France", "street": "1 rue Alsace-Lorraine", "contact": "61.77.6555"},
    {"id": 88, "name": "Messner Shopping Network", "city": "Frankfurt, Germany", "street": "Magazinweg 7", "contact": "069-0555984"},
    {"id": 89, "name": "Amica Models & Co.", "city": "Torino, Italy", "street": "Via Monte Bianco 34", "contact": "011-4988555"},
    {"id": 90, "name": "Lyon Souveniers", "city": "Paris, France", "street": "27 rue du Colonel Pierre Avia", "contact": "+33 1 46 62 7555"},
    {"id": 91, "name": "Auto Associés & Cie.", "city": "Versailles, France", "street": "67, avenue de l'Europe", "contact": "30.59.8555"},
    {"id": 92, "name": "Toms Spezialitäten, Ltd", "city": "Köln, Germany", "street": "Mehrheimerstr. 369", "contact": "0221-5554327"},
    {"id": 93, "name": "Royal Canadian Collectables, Ltd.", "city": "Tsawassen, Canada", "street": "23 Tsawassen Blvd.", "contact": "(604) 555-4555"},
    {"id": 94, "name": "Franken Gifts, Co", "city": "München, Germany", "street": "Berliner Platz 43", "contact": "089-0877555"},
    {"id": 95, "name": "Anna's Decorations, Ltd", "city": "North Sydney, Australia", "street": "201 Miller Street", "contact": "02 9936 8555"},
    {"id": 96, "name": "Rovelli Gifts", "city": "Bergamo, Italy", "street": "Via Ludovico il Moro 22", "contact": "035-640555"},
    {"id": 97, "name": "Souveniers And Things Co.", "city": "Chatswood, Australia", "street": "Monitor Money Building", "contact": "+61 2 9495 8555"},
    {"id": 98, "name": "Marta's Replicas Co.", "city": "Cambridge, MA", "street": "39323 Spinnaker Dr.", "contact": "6175558555"},
    {"id": 99, "name": "BG&E Collectables", "city": "Fribourg, Switzerland", "street": "Rte des Arsenaux 41", "contact": "+41 26 425 50 01"},
    {"id": 100, "name": "Vida Sport, Ltd", "city": "Genève, Switzerland", "street": "Grenzacherweg 237", "contact": "0897-034555"},
    {"id": 101, "name": "Norway Gifts By Mail, Co.", "city": "Oslo, Norway", "street": "Drammensveien 126A", "contact": "+47 2212 1555"},
    {"id": 102, "name": "Schuyler Imports", "city": "Amsterdam, Netherlands", "street": "Kingsfordweg 151", "contact": "+31 20 491 9555"},
    {"id": 103, "name": "Der Hund Imports", "city": "Berlin, Germany", "street": "Obere Str. 57", "contact": "030-0074555"},
    {"id": 104, "name": "Oulu Toy Supplies, Inc.", "city": "Oulu, Finland", "street": "Torikatu 38", "contact": "981-443655"},
    {"id": 105, "name": "Petit Auto", "city": "Bruxelles, Belgium", "street": "Rue Joseph-Bens 532", "contact": "(02) 5554 67"},
    {"id": 106, "name": "Mini Classics", "city": "White Plains, NY", "street": "3758 North Pendale Street", "contact": "9145554562"},
    {"id": 107, "name": "Mini Creations Ltd.", "city": "New Bedford, MA", "street": "4575 Hillside Dr.", "contact": "5085559555"},
    {"id": 108, "name": "Corporate Gift Ideas Co.", "city": "San Francisco, CA", "street": "7734 Strong St.", "contact": "6505551386"},
    {"id": 109, "name": "Down Under Souveniers, Inc", "city": "Auckland , New Zealand", "street": "162-164 Grafton Road", "contact": "+64 9 312 5555"},
    {"id": 110, "name": "Stylish Desk Decors, Co.", "city": "London, UK", "street": "35 King George", "contact": "(171) 555-0297"},
    {"id": 111, "name": "Tekni Collectables Inc.", "city": "Newark, NJ", "street": "7476 Moss Rd.", "contact": "2015559350"},
    {"id": 112, "name": "Australian Gift Network, Co", "city": "South Brisbane, Australia", "street": "31 Duncan St. West End", "contact": "61-7-3844-6555"},
    {"id": 113, "name": "Suominen Souveniers", "city": "Espoo, Finland", "street": "Software Engineering Center", "contact": "+358 9 8045 555"},
    {"id": 114, "name": "Cramer Spezialitäten, Ltd", "city": "Brandenburg, Germany", "street": "Maubelstr. 90", "contact": "0555-09555"},
    {"id": 115, "name": "Classic Gift Ideas, Inc", "city": "Philadelphia, PA", "street": "782 First Street", "contact": "2155554695"},
    {"id": 116, "name": "CAF Imports", "city": "Madrid, Spain", "street": "Merchants House", "contact": "+34 913 728 555"},
    {"id": 117, "name": "Men 'R' US Retailers, Ltd.", "city": "Los Angeles, CA", "street": "6047 Douglas Av.", "contact": "2155554369"},
    {"id": 118, "name": "Asian Treasures, Inc.", "city": "Cork, Ireland", "street": "8 Johnstown Road", "contact": "2967 555"},
    {"id": 119, "name": "Marseille Mini Autos", "city": "Marseille, France", "street": "12, rue des Bouchers", "contact": "91.24.4555"},
    {"id": 120, "name": "Reims Collectables", "city": "Reims, France", "street": "59 rue de l'Abbaye", "contact": "26.47.1555"},
    {"id": 121, "name": "SAR Distributors, Co", "city": "Hatfield, South Africa", "street": "1250 Pretorius Street", "contact": "+27 21 550 3555"},
    {"id": 122, "name": "GiftsForHim.com", "city": "Auckland, New Zealand", "street": "199 Great North Road", "contact": "64-9-3763555"},
    {"id": 123, "name": "Kommission Auto", "city": "Münster, Germany", "street": "Luisenstr. 48", "contact": "0251-555259"},
    {"id": 124, "name": "Gifts4AllAges.com", "city": "Boston, MA", "street": "8616 Spinnaker Dr.", "contact": "6175559555"},
    {"id": 125, "name": "Online Diecast Creations Co.", "city": "Nashua, NH", "street": "2304 Long Airport Avenue", "contact": "6035558647"},
    {"id": 126, "name": "Lisboa Souveniers, Inc", "city": "Lisboa, Portugal", "street": "Jardim das rosas n. 32", "contact": "(1) 354-2555"},
    {"id": 127, "name": "Precious Collectables", "city": "Bern, Switzerland", "street": "Hauptstr. 29", "contact": "0452-076555"},
    {"id": 128, "name": "Collectables For Less Inc.", "city": "Brickhaven, MA", "street": "7825 Douglas Av.", "contact": "6175558555"},
    {"id": 129, "name": "Royale Belge", "city": "Charleroi, Belgium", "street": "Boulevard Tirou, 255", "contact": "(071) 23 67 2555"},
    {"id": 130, "name": "Salzburg Collectables", "city": "Salzburg, Austria", "street": "Geislweg 14", "contact": "6562-9555"},
    {"id": 131, "name": "Cruz & Sons Co.", "city": "Makati City, Philippines", "street": "15 McCallum Street", "contact": "+63 2 555 3587"},
    {"id": 132, "name": "L'ordine Souveniers", "city": "Reggio Emilia, Italy", "street": "Strada Provinciale 124", "contact": "0522-556555"},
    {"id": 133, "name": "Tokyo Collectables, Ltd", "city": "Minato-ku, Japan", "street": "2-2-8 Roppongi", "contact": "+81 3 3584 0555"},
    {"id": 134, "name": "Auto Canal+ Petit", "city": "Paris, France", "street": "25, rue Lauriston", "contact": "(1) 47.55.6555"},
    {"id": 135, "name": "Stuttgart Collectable Exchange", "city": "Stuttgart, Germany", "street": "Adenauerallee 900", "contact": "0711-555361"},
    {"id": 136, "name": "Extreme Desk Decorations, Ltd", "city": "Wellington, New Zealand", "street": "101 Lambton Quay", "contact": "04 499 9555"},
    {"id": 137, "name": "Bavarian Collectables Imports, Co.", "city": "Munich, Germany", "street": "Hansastr. 15", "contact": "+49 89 61 08 9555"},
    {"id": 138, "name": "Classic Legends Inc.", "city": "NYC, NY", "street": "5905 Pompton St.", "contact": "2125558493"},
    {"id": 139, "name": "Feuer Online Stores, Inc", "city": "Leipzig, Germany", "street": "Heerstr. 22", "contact": "0342-555176"},
    {"id": 140, "name": "Gift Ideas Corp.", "city": "Glendale, CT", "street": "2440 Pompton St.", "contact": "2035554407"},
    {"id": 141, "name": "Scandinavian Gift Ideas", "city": "Bräcke, Sweden", "street": "Åkergatan 24", "contact": "0695-34 6555"},
    {"id": 142, "name": "The Sharp Gifts Warehouse", "city": "San Jose, CA", "street": "3086 Ingle Ln.", "contact": "4085553659"},
    {"id": 143, "name": "Mini Auto Werke", "city": "Graz, Austria", "street": "Kirchgasse 6", "contact": "7675-3555"},
    {"id": 144, "name": "Super Scale Inc.", "city": "New Haven, CT", "street": "567 North Pendale Street", "contact": "2035559545"},
    {"id": 145, "name": "Microscale Inc.", "city": "NYC, NY", "street": "5290 North Pendale Street", "contact": "2125551957"},
    {"id": 146, "name": "Corrida Auto Replicas, Ltd", "city": "Madrid, Spain", "street": "C/ Araquil", "contact": "(91) 555 22 82"},
    {"id": 147, "name": "Warburg Exchange", "city": "Aachen, Germany", "street": "Walserweg 21", "contact": "0241-039123"},
    {"id": 148, "name": "FunGiftIdeas.com", "city": "New Bedford, MA", "street": "1785 First Street", "contact": "5085552555"},
    {"id": 149, "name": "Anton Designs, Ltd.", "city": "Madrid, Spain", "street": "c/ Gobelas, 19-1 Urb. La Florida", "contact": "+34 913 728555"},
    {"id": 150, "name": "Australian Collectables, Ltd", "city": "Glen Waverly, Australia", "street": "7 Allen Street", "contact": "61-9-3844-6555"},
    {"id": 151, "name": "Frau da Collezione", "city": "Milan, Italy", "street": "20093 Cologno Monzese", "contact": "+39 022515555"},
    {"id": 152, "name": "West Coast Collectables Co.", "city": "Burbank, CA", "street": "3675 Furth Circle", "contact": "3105553722"},
    {"id": 153, "name": "Mit Vergnügen & Co.", "city": "Mannheim, Germany", "street": "Forsterstr. 57", "contact": "0621-08555"},
    {"id": 154, "name": "Kremlin Collectables, Co.", "city": "Saint Petersburg, Russia", "street": "2 Pobedy Square", "contact": "+7 812 293 0521"},
    {"id": 155, "name": "Raanan Stores, Inc", "city": "Herzlia, Israel", "street": "3 Hagalim Blv.", "contact": "+972 9 959 8555"},
    {"id": 156, "name": "Iberia Gift Imports, Corp.", "city": "Sevilla, Spain", "street": "C/ Romero, 33", "contact": "(95) 555 82 82"},
    {"id": 157, "name": "Motor Mint Distributors Inc.", "city": "Philadelphia, PA", "street": "11328 Douglas Av.", "contact": "2155559857"},
    {"id": 158, "name": "Signal Collectibles Ltd.", "city": "Brisbane, CA", "street": "2793 Furth Circle", "contact": "4155554312"},
    {"id": 159, "name": "Double Decker Gift Stores, Ltd", "city": "London, UK", "street": "120 Hanover Sq.", "contact": "(171) 555-7555"},
    {"id": 160, "name": "Diecast Collectables", "city": "Boston, MA", "street": "6251 Ingle Ln.", "contact": "6175552555"},
    {"id": 161, "name": "Kelly's Gift Shop", "city": "Auckland , New Zealand", "street": "Arenales 1938 3'A'", "contact": "+64 9 5555500"},
    {"id": 162, "name": "customer", "city": "Chicago , Illinois", "street": "1602 Doolittle Ln", "contact": "+1 857"},
    {"id": 163, "name": "admin", "city": "New York , New York", "street": "123 Jane Street", "contact": "+1 123 234 2342"},
    {"id": 164, "name": "worker", "city": "Los Angeles , California Zealand", "street": "1780 Citadel Av", "contact": "+1 234 124 1241"}
]

parts_data = [
    {"number": 1, "description": "windshield w/ polymer", "price": 178.76, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/shi.jpg", "quantity": 20},
    {"number": 2, "description": "wiper blade pair", "price": 23.37, "weight": 2.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/wip.jpg", "quantity": 24},
    {"number": 3, "description": "solenoid", "price": 36.58, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/sol.jpg", "quantity": 100},
    {"number": 4, "description": "tiresome mettle", "price": 157.46, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/met.jpg", "quantity": 11},
    {"number": 5, "description": "bucket seat pair", "price": 315.94, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/sea.jpg", "quantity": 234},
    {"number": 6, "description": "5 point harness", "price": 177.79, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/har.jpg", "quantity": 2},
    {"number": 7, "description": "turbo intake valve", "price": 659.83, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/val.jpg", "quantity": 25},
    {"number": 8, "description": "supercharger", "price": 711.14, "weight": 99.99, "picture_path_url": "http://blitz.cs.niu.edu/pics/anc.jpg", "quantity": 67},
    {"number": 9, "description": "inter cooler sweep", "price": 202.17, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/int.jpg", "quantity": 112},
    {"number": 10, "description": "gas cap - chrome", "price": 25.38, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/gas.jpg", "quantity": 46},
    {"number": 11, "description": "chrome brake pedals kit-manual", "price": 45.71, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/bra.jpg", "quantity": 111},
    {"number": 12, "description": "chrome brake pedals kit-automatic", "price": 41.65, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/bra.jpg", "quantity": 36},
    {"number": 13, "description": "intel inside window decal", "price": 2.03, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/itl.jpg", "quantity": 23},
    {"number": 14, "description": "niu alumni window decal", "price": 1.85, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/niu.jpg", "quantity": 67},
    {"number": 15, "description": "air freshener - lemon", "price": 1.85, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/lem.jpg", "quantity": 89},
    {"number": 16, "description": "air freshener - cherry", "price": 1.85, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/che.jpg", "quantity": 14},
    {"number": 17, "description": "air freshener - new car smell", "price": 2.06, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/usa.jpg", "quantity": 10},
    {"number": 18, "description": "cargo net (new model)", "price": 25.36, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/net.jpg", "quantity": 20},
    {"number": 19, "description": "trunk liner", "price": 25.38, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/tru.jpg", "quantity": 30},
    {"number": 20, "description": "floor mat - driver side", "price": 13.21, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/mat.jpg", "quantity": 40},
    {"number": 21, "description": "floor mat - passenger side", "price": 13.21, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/mat.jpg", "quantity": 50},
    {"number": 22, "description": "car detail kit", "price": 88.38, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/cdk.jpg", "quantity": 60},
    {"number": 23, "description": "tachometer", "price": 30.48, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/tach.jpg", "quantity": 70},
    {"number": 24, "description": "speedometer mph edition", "price": 34.55, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/spe.jpg", "quantity": 80},
    {"number": 25, "description": "gps navigation", "price": 152.39, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/gps.jpg", "quantity": 90},
    {"number": 26, "description": "CD/DVD/DB holder", "price": 20.31, "weight": 0.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/dvd.jpg", "quantity": 100},
    {"number": 27, "description": "car charger - micro usb, 2 ft", "price": 17.26, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/cha.jpg", "quantity": 100},
    {"number": 28, "description": "Backup camera peephole", "price": 10.12, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/bac.jpg", "quantity": 90},
    {"number": 30, "description": "USB car adapter, NaviPro 2.1", "price": 220.45, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/usb.jpg", "quantity": 80},
    {"number": 31, "description": "Reverse Sensor, mitigatable", "price": 50.75, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/tac.jpg", "quantity": 70},
    {"number": 33, "description": "Stylish Part: 25-11-07 08:52", "price": 101.58, "weight": 99.99, "picture_path_url": "http://blitz.cs.niu.edu/pics/033-1.jpg", "quantity": 60},
    {"number": 40, "description": "1969 Harley Davidson Ultimate Chopper", "price": 49.59, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 50},
    {"number": 41, "description": "1952 Alpine Renault 1300", "price": 100.16, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 40},
    {"number": 42, "description": "1996 Moto Guzzi 1100i", "price": 70.08, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 30},
    {"number": 43, "description": "2003 Harley-Davidson Eagle Drag Bike", "price": 92.47, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/any.jpg", "quantity": 20},
    {"number": 44, "description": "1972 Alfa Romeo GTA", "price": 87.06, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 10},
    {"number": 45, "description": "1962 LanciaA Delta 16V", "price": 105.05, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 5},
    {"number": 46, "description": "1968 Ford Mustang", "price": 96.84, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 100},
    {"number": 47, "description": "2001 Ferrari Enzo", "price": 97.11, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 24},
    {"number": 48, "description": "1958 Setra Bus", "price": 79.14, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/bus.jpg", "quantity": 123},
    {"number": 49, "description": "2002 Suzuki XERO", "price": 67.32, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 23},
    {"number": 50, "description": "1969 Corvair Monza", "price": 90.55, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 33},
    {"number": 51, "description": "1968 Dodge Charger", "price": 76.36, "weight": 99.99, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 44},
    {"number": 52, "description": "1969 Ford Falcon", "price": 84.38, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 55},
    {"number": 53, "description": "1970 Plymouth Hemi Cuda", "price": 32.42, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 60},
    {"number": 54, "description": "1957 Chevy Pickup", "price": 56.59, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 100},
    {"number": 55, "description": "1969 Dodge Charger", "price": 59.66, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 17},
    {"number": 56, "description": "1940 Ford Pickup Truck", "price": 59.25, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 16},
    {"number": 57, "description": "1993 Mazda RX-7", "price": 84.84, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 19},
    {"number": 58, "description": "1937 Lincoln Berline", "price": 61.58, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 22},
    {"number": 59, "description": "1936 Mercedes-Benz 500K Special Roadster", "price": 24.64, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 32},
    {"number": 60, "description": "1965 Aston Martin DB5", "price": 67.01, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 34},
    {"number": 61, "description": "1980s Black Hawk Helicopter", "price": 78.50, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/heli.jpg", "quantity": 35},
    {"number": 62, "description": "1917 Grand Touring Sedan", "price": 88.07, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 41},
    {"number": 63, "description": "1948 Porsche 356-A Roadster", "price": 54.77, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 41},
    {"number": 64, "description": "1995 Honda Civic", "price": 95.39, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 42},
    {"number": 65, "description": "1998 Chrysler Plymouth Prowler", "price": 103.14, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 23},
    {"number": 66, "description": "1911 Ford Town Car", "price": 33.83, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 23},
    {"number": 67, "description": "1964 Mercedes Tour Bus", "price": 76.06, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/bus.jpg", "quantity": 11},
    {"number": 68, "description": "1932 Model A Ford J-Coupe", "price": 59.42, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 55},
    {"number": 69, "description": "1926 Ford Fire Engine", "price": 25.32, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 11},
    {"number": 70, "description": "P-51-D Mustang", "price": 49.77, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 11},
    {"number": 71, "description": "1936 Harley Davidson El Knucklehead", "price": 24.62, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 44},
    {"number": 72, "description": "1928 Mercedes-Benz SSK", "price": 73.72, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 11},
    {"number": 73, "description": "1999 Indy 500 Monte Carlo SS", "price": 57.66, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 11},
    {"number": 74, "description": "1913 Ford Model T Speedster", "price": 61.75, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 22},
    {"number": 75, "description": "1934 Ford V8 Coupe", "price": 34.89, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 32},
    {"number": 76, "description": "1999 Yamaha Speed Boat", "price": 52.43, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 112},
    {"number": 77, "description": "18th Century Vintage Horse Carriage", "price": 61.68, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/horse.jpg", "quantity": 112},
    {"number": 78, "description": "1903 Ford Model A", "price": 69.39, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 22},
    {"number": 79, "description": "1992 Ferrari 360 Spider red", "price": 79.14, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 44},
    {"number": 80, "description": "1985 Toyota Supra", "price": 57.91, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 33},
    {"number": 81, "description": "Collectable Wooden Train", "price": 68.65, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/train.jpg", "quantity": 21},
    {"number": 82, "description": "1969 Dodge Super Bee", "price": 49.82, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 67},
    {"number": 83, "description": "1917 Maxwell Touring Car", "price": 58.44, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 89},
    {"number": 84, "description": "1976 Ford Gran Torino", "price": 74.67, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 77},
    {"number": 85, "description": "1948 Porsche Type 356 Roadster", "price": 63.16, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 65},
    {"number": 86, "description": "1957 Vespa GS150", "price": 33.48, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 54},
    {"number": 87, "description": "1941 Chevrolet Special Deluxe Cabriolet", "price": 65.61, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 33},
    {"number": 88, "description": "1970 Triumph Spitfire", "price": 93.39, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 33},
    {"number": 89, "description": "1932 Alfa Romeo 8C2300 Spider Sport", "price": 43.96, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 78},
    {"number": 90, "description": "1904 Buick Runabout", "price": 53.50, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 89},
    {"number": 91, "description": "1940s Ford truck", "price": 86.11, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 21},
    {"number": 92, "description": "1939 Cadillac Limousine", "price": 23.51, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 22},
    {"number": 93, "description": "1957 Corvette Convertible", "price": 71.04, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 33},
    {"number": 94, "description": "1957 Ford Thunderbird", "price": 34.75, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 34},
    {"number": 95, "description": "1970 Chevy Chevelle SS 454", "price": 50.02, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 44},
    {"number": 96, "description": "1970 Dodge Coronet", "price": 32.89, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 55},
    {"number": 97, "description": "1997 BMW R 1100 S", "price": 61.83, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 77},
    {"number": 98, "description": "1966 Shelby Cobra 427 S/C", "price": 29.64, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 88},
    {"number": 99, "description": "1928 British Royal Navy Airplane", "price": 67.80, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 89},
    {"number": 100, "description": "1939 Chevrolet Deluxe Coupe", "price": 22.92, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 41},
    {"number": 101, "description": "1960 BSA Gold Star DBD34", "price": 37.91, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 123},
    {"number": 102, "description": "18th century schooner", "price": 83.65, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 31},
    {"number": 103, "description": "1938 Cadillac V-16 Presidential Limousine", "price": 20.94, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 21},
    {"number": 104, "description": "1962 Volkswagen Microbus", "price": 62.31, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/bus.jpg", "quantity": 33},
    {"number": 105, "description": "1982 Ducati 900 Monster", "price": 47.85, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 67},
    {"number": 106, "description": "1949 Jaguar XK 120", "price": 48.00, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 89},
    {"number": 107, "description": "1958 Chevy Corvette Limited Edition", "price": 16.16, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 21},
    {"number": 108, "description": "1900s Vintage Bi-Plane", "price": 34.78, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/any.jpg", "quantity": 33},
    {"number": 109, "description": "1952 Citroen-15CV", "price": 73.98, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 33},
    {"number": 110, "description": "1982 Lamborghini Diablo", "price": 16.50, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 56},
    {"number": 111, "description": "1912 Ford Model T Delivery Wagon", "price": 47.65, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 78},
    {"number": 112, "description": "1969 Chevrolet Camaro Z28", "price": 51.31, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 44},
    {"number": 113, "description": "1971 Alpine Renault 1600s", "price": 39.19, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 33},
    {"number": 114, "description": "1937 Horch 930V Limousine", "price": 26.71, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 12},
    {"number": 115, "description": "2002 Chevy Corvette", "price": 63.10, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 12},
    {"number": 116, "description": "1940 Ford Delivery Sedan", "price": 49.41, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 12},
    {"number": 117, "description": "1956 Porsche 356A Coupe", "price": 99.87, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 12},
    {"number": 118, "description": "Corsair F4U ( Bird Cage)", "price": 29.80, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/cor.jpg", "quantity": 32},
    {"number": 119, "description": "1936 Mercedes Benz 500k Roadster", "price": 22.11, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 21},
    {"number": 120, "description": "1992 Porsche Cayenne Turbo Silver", "price": 70.89, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 23},
    {"number": 121, "description": "1936 Chrysler Airflow", "price": 58.39, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 55},
    {"number": 122, "description": "1900s Vintage Tri-Plane", "price": 36.80, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/any.jpg", "quantity": 33},
    {"number": 123, "description": "1961 Chevrolet Impala", "price": 32.83, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 24},
    {"number": 124, "description": "1980 GM Manhattan Express", "price": 60.70, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 31},
    {"number": 125, "description": "1997 BMW F650 ST", "price": 75.34, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 21},
    {"number": 126, "description": "1982 Ducati 996 R", "price": 27.17, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 43},
    {"number": 127, "description": "1954 Greyhound Scenicruiser", "price": 29.24, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/bus.jpg", "quantity": 12},
    {"number": 128, "description": "1950 Chicago Surface Lines Streetcar", "price": 30.08, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/scar.jpg", "quantity": 12},
    {"number": 129, "description": "1996 Peterbilt 379 Stake Bed with Outrigger", "price": 37.83, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/peter.jpg", "quantity": 12},
    {"number": 130, "description": "1928 Ford Phaeton Deluxe", "price": 37.17, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ford.jpg", "quantity": 12},
    {"number": 131, "description": "1974 Ducati 350 Mk3 Desmo", "price": 63.18, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 12},
    {"number": 132, "description": "1930 Buick Marquette Phaeton", "price": 30.47, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 12},
    {"number": 133, "description": "Diamond T620 Semi-Skirted Tanker", "price": 76.87, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12},
    {"number": 134, "description": "1962 City of Detroit Streetcar", "price": 42.20, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/scar.jpg", "quantity": 12},
    {"number": 135, "description": "2002 Yamaha YZR M1", "price": 38.47, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/mop.jpg", "quantity": 12},
    {"number": 136, "description": "The Schooner Bluenose", "price": 38.28, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12},
    {"number": 137, "description": "American Airlines: B767-300", "price": 57.58, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 12},
    {"number": 138, "description": "The Mayflower", "price": 48.74, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12},
    {"number": 139, "description": "HMS Bounty", "price": 44.84, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12},
    {"number": 140, "description": "America West Airlines B757-200", "price": 77.44, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 12},
    {"number": 141, "description": "The USS Constitution Ship", "price": 38.25, "weight": 0.55, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12},
    {"number": 142, "description": "1982 Camaro Z28", "price": 52.38, "weight": 1.95, "picture_path_url": "http://blitz.cs.niu.edu/pics/car.jpg", "quantity": 12},
    {"number": 143, "description": "ATA: B757-300", "price": 66.78, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 12},
    {"number": 144, "description": "F/A 18 Hornet 1/72", "price": 61.24, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 12},
    {"number": 145, "description": "The Titanic", "price": 57.50, "weight": 3.50, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12},
    {"number": 146, "description": "The Queen Mary", "price": 60.37, "weight": 12.45, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12},
    {"number": 147, "description": "American Airlines: MD-11S", "price": 40.83, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 12},
    {"number": 148, "description": "Boeing X-32A JSF", "price": 36.90, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/air.jpg", "quantity": 12},
    {"number": 149, "description": "Pont Yacht", "price": 37.48, "weight": 2.00, "picture_path_url": "http://blitz.cs.niu.edu/pics/ship.jpg", "quantity": 12}
]